### ISSUE TITLE
vous avez oublié de mettre "vendor/" dans .gitignore

### ISSUE THREAD

**Issue by JamesMcAvoy** [ludwhe/site_bde#1]
c'est gênant

**Comment by wewxd** [comment]
@JamesMcAvoy le vendor est dans le gitignore par défaut généré par laravel quand tu crées un nouveau projet
Le problème est qu'ils ont ` git clone https://github.com/laravel/laravel `
Au lieu de ` laravel new projet `
Le vendor dans gitignore n'est pas la seule chose qui manque, et il y a des choses en trop.

Vous devriez passer votre projet en privé parce que @JamesMcAvoy n'est pas très gentil :/

**Comment by ludwhe** [comment]
c'est fait pour, oui ça pue mais w/e

**Comment by AnthonyHadware** [comment]
bah non

**Comment by JamesMcAvoy** [comment]
donc t'as 5 000 fichiers sur chaque commit mais c'est fait pour
