### ISSUE TITLE
repo en public

### ISSUE THREAD

**Issue by AnthonyHadware** [ludwhe/site_bde#2]
![filipe](https://user-images.githubusercontent.com/23233171/38489570-161c0002-3be7-11e8-872b-1245e9796edf.jpg)

**Comment by JamesMcAvoy** [comment]
c'est le meilleur en PHP de notre promo lui

**Comment by AnthonyHadware** [comment]
il a dit votre site était nul

**Comment by AnthonyHadware** [comment]
![filipe](https://user-images.githubusercontent.com/23233171/38489665-567bb4b2-3be7-11e8-959a-b83cd8163794.png)

quand tu vois un repo en **public**

**Comment by JamesMcAvoy** [comment]
![](https://user-images.githubusercontent.com/23233171/38489665-567bb4b2-3be7-11e8-959a-b83cd8163794.png)

quand tu sais pas close une issue

**Comment by AnthonyHadware** [comment]
![filipe](https://user-images.githubusercontent.com/23233171/38497064-115583a4-3c00-11e8-95dd-d424620c1e89.jpg)
